//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoClicker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class HotkeySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotkeySettings defaultInstance = ((HotkeySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotkeySettings())));
        
        public static HotkeySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("117")]
        public int StartHotkey {
            get {
                return ((int)(this["StartHotkey"]));
            }
            set {
                this["StartHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int StopHotkey {
            get {
                return ((int)(this["StopHotkey"]));
            }
            set {
                this["StopHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("119")]
        public int ToggleHotkey {
            get {
                return ((int)(this["ToggleHotkey"]));
            }
            set {
                this["ToggleHotkey"] = value;
            }
        }
    }
}
